[workspace]
members = ["editor", "app", "config"]
resolver = "2"

[workspace.package]
version = "0.2.36"
repository = "https://github.com/bons0002/rust-text-editor"
license = "GPL OR MIT"

[workspace.dependencies]
rayon = "1.10"
ratatui = "0.26"
crossterm = "0.27"
unicode-segmentation = "1.11"