[workspace]

members = ["editor", "app", "config"]

[workspace.package]

name = "rust-text-editor" # Temp
version = "0.2.10"
repository = "https://github.com/bons0002/rust-text-editor"
license = "GPL OR MIT"