[package]
name = "app"
version.workspace = true
edition = "2021"

[dependencies]
ratatui = {workspace = true}
crossterm = {workspace = true}
editor = { path = "../editor" }
config = { path = "../config" }