[package]
name = "editor"
version.workspace = true
edition = "2021"

[dependencies]
rayon = {workspace = true}
ratatui = {workspace = true}
crossterm = {workspace = true}
unicode-segmentation = {workspace = true}
config = { path = "../config" }